api/urls.py
from django.urls import path

from api.views import ( GetServicesByDepartmentId,  VisitsByServiceData,
                        VisitsForLastWeekData, GetDepartmentById)
# from api.views import get_doctors_list

urlpatterns = [
    # chart js data
    path('data/visits-by-service/', VisitsByServiceData.as_view(), name="visits-by-service-data-view"),
    path('data/visits-for-last-week/', VisitsForLastWeekData.as_view(), name="visits-for-last-week-data-view"),
    # services
    path('services/list/<int:department_id>/', GetServicesByDepartmentId.as_view(), name="services-by-dep-id-view"),
    # departments
    path('department/<int:department_id>/', GetDepartmentById.as_view(), name='get-department-view'),
    # doctors
    # path('doctors/list/', get_doctors_list, name='get-doctors-api'),
]

configs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from med_center.views import main_page_view, appointment_form, about_page, departments_page, contacts_page


urlpatterns = [
    # main panel
    path('', main_page_view, name='main-page'),
    path('appointment-form/', appointment_form, name='appointment-form-view'),
    path('about/', about_page, name='about-page'),
    path('departments/', departments_page, name='departments-page'),
    path('contacts/', contacts_page, name='contacts-page'),
    # django select2
    path('select2/', include('django_select2.urls'), name='select2-view'),
    # admin panel
    path('admin/', admin.site.urls),
    # applications' urls
    path('profiles/', include("profiles.urls")),
    path('samples/', include("samples.urls")),
    path('visits/', include("visit.urls")),
    path('api/', include("api.urls"))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

department/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from med_center.models import MedicalCenter


class Department(models.Model):
    title = models.CharField(max_length=500)
    description = models.TextField()
    image = models.ImageField(upload_to='department/', help_text="only little icons")
    med_center = models.ForeignKey(MedicalCenter, on_delete=models.CASCADE,
                                   related_name="departments")

    class Meta:
        verbose_name = _("Department")
        verbose_name_plural = _("Departments")

    def __str__(self):
        return f"{self.title}"

med_center/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class MedicalCenter(models.Model):
    title = models.CharField(max_length=200)
    tagline = models.CharField(max_length=500, null=True, blank=True)
    description = models.TextField()
    email = models.EmailField(null=True, blank=True)
    doctor_default_image = models.ImageField(upload_to="med-center-photos/",
                                             null=True, blank=True)
    patient_default_image = models.ImageField(upload_to="med-center-photos/",
                                              null=True, blank=True)
    insta_link = models.CharField(max_length=800, blank=True, null=True)
    facebook_link = models.CharField(max_length=800, blank=True, null=True)
    youtube_link = models.CharField(max_length=800, blank=True, null=True)

    class Meta:
        verbose_name = _("Medical Center")
        verbose_name_plural = _("Medical Centers")

    def __str__(self):
        return f"{self.title}"


class MedCenterPhoto(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to="med-center-photos/")
    is_logo = models.BooleanField(default=False)
    medical_center = models.ForeignKey(MedicalCenter, on_delete=models.CASCADE,
                                       related_name="photos")

    class Meta:
        verbose_name = _("Med-Center Photo")
        verbose_name_plural = _("Med-Center Photos")

    def __str__(self):
        return f"{self.title}"


class ScheduleTime(models.Model):
    med_center = models.ForeignKey(MedicalCenter, on_delete=models.CASCADE,
                                   related_name="schedule_times")
    title = models.CharField(max_length=30)
    start_time = models.TimeField(null=True, blank=True)
    end_time = models.TimeField(null=True, blank=True)
    is_weekend = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Schedule Time"
        verbose_name_plural = "Schedule Times"

    def __str__(self):
        return f"{self.title}  start: {self.start_time}  end; {self.end_time}"

profiles/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save, post_delete
from django.utils.translation import gettext_lazy as _


from profiles.choices import ROLE, GENDER

from department.models import Department


class User(AbstractUser):
    username = models.CharField(max_length=200, unique=True)
    role = models.PositiveSmallIntegerField(choices=ROLE, default=0)
    gender = models.PositiveSmallIntegerField(choices=GENDER, default=1)
    full_name = models.CharField(max_length=150)
    birth_date = models.DateField(null=True, blank=True)
    email = models.EmailField("Email", max_length=100, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f"{self.full_name} {self.birth_date}"


class Doctor(models.Model):
    profile_id = models.OneToOneField(User,
                                      on_delete=models.CASCADE,
                                      primary_key=True)
    department_id = models.ForeignKey(Department,
                                      null=True, blank=True,
                                      on_delete=models.CASCADE,
                                      related_name="doctors")
    experience = models.IntegerField(default=1)
    salary = models.DecimalField(max_digits=10, decimal_places=2,
                                 null=True, blank=True)
    image = models.ImageField(upload_to="doctors/",
                              null=True, blank=True)

    class Meta:
        verbose_name = _("Doctor")
        verbose_name_plural = _("Doctors")

    def __str__(self):
        return f"{self.profile_id.full_name} ({self.department_id})"


class UserPhoneNumber(models.Model):
    number = models.CharField(max_length=40)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Patient(models.Model):
    profile_id = models.OneToOneField(User, on_delete=models.CASCADE,
                                      primary_key=True,
                                      verbose_name=_("Profile"))
    address = models.CharField(null=True, blank=True,
                               max_length=255, verbose_name=_("Address"))
    first_password = models.CharField(null=True, blank=True,
                                      max_length=255, verbose_name=_("Initial Password"))

    class Meta:
        verbose_name = _("Patient")
        verbose_name_plural = _("Patients")

    def __str__(self):
        return f"{self.profile_id.full_name}"


# function to create doctor or patient after creating User
def create_doctor_or_patient(sender, **kwargs):
    user = kwargs["instance"]
    if kwargs["created"]:
        if user.role == 0:
            Doctor.objects.create(profile_id=user)
        elif user.role == 1:
            Patient.objects.create(profile_id=user)


post_save.connect(create_doctor_or_patient, sender=User)

med_center/forms.py
from django import forms

from profiles.models import Doctor


class AppointmentForm(forms.Form):
    patient_full_name = forms.CharField(
        required=True,
        label="Ф.И.О пациента",
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Ф.И.О *',
                'class': "form-control", }
        )
    )
    patient_phone_number = forms.CharField(
        required=True,
        label="Номер телефона",
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Номер телефона',
                'class': "form-control",
                'id': 'patient-phone-number'
            }
        )
    )
    doctor_choice = forms.ModelChoiceField(
        required=False,
        queryset=Doctor.objects.filter(profile_id__is_superuser=False),
        label="Выберите Доктора",
        widget=forms.Select(
            attrs={
                'placeholder': 'Выберите доктора',
                'class': 'form-control',
                'id': 'doctor-choice',
                'style': 'select option {'
                         'background: #cccccc'
                         '}'
            }
        )
    )
    date_time = forms.DateTimeField(
        input_formats=['%d/%m/%Y %H:%M'],
        required=True,
        widget=forms.DateTimeInput(
            format='%d/%m/%Y %H:%M',
            attrs={
                'placeholder': 'Дата и Время *',
                'class': 'form-control date',
                'id': 'probootstrap-date'
            }
        )
    )
    patient_preference = forms.CharField(
        required=False,
        label="Предпочтения пациента",
        widget=forms.Textarea(
            attrs={
                'width': "100%", 'cols': "100", 'rows': "5",
                'placeholder': 'Ваши предпочтения',
                'class': "form-control", }
        )
    )

department/views.py
from django.shortcuts import render

# Create your views here.

med_center/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.mail import send_mail
from django.conf import settings
from django.template.loader import render_to_string
from django.utils.html import strip_tags

from med_center.models import MedicalCenter, MedCenterPhoto
from med_center.forms import AppointmentForm

from branch.models import Branch, BranchPhoneNumber
from profiles.models import Doctor, User
from department.models import Department
from services.models import Service
from visit.models import Review


def appointment_form(request):
    if request.method == "POST":
        form = AppointmentForm(request.POST or None)
        if form.is_valid():
            print("Email sent")
            admin_user_email = User.objects.get(username='admin').email
            mail_context = {
                'patient_full_name': form.cleaned_data['patient_full_name'],
                'patient_phone_number': form.cleaned_data['patient_phone_number'],
                'date_time': form.cleaned_data['date_time'],
                'patient_preference': form.cleaned_data['patient_preference'],
                'doctor_choice': form.cleaned_data['doctor_choice'],
            }
            html_message = render_to_string('pdf/mail_template.html', context=mail_context)
            plain_text_message = strip_tags(html_message)

            send_mail('Test message', plain_text_message,
                      settings.EMAIL_HOST_USER, [admin_user_email, ],
                      html_message=html_message)
            messages.success(request, "Запись произошла успешно!")
            return redirect(main_page_view)
        print("Appointment Form Is Not Valid")
        print(form.errors)
        messages.error(request, "Произошла ошибка при записи. Проверьте формат даты")
        return redirect(main_page_view)


def about_page(request):
    # med center
    med_center = MedicalCenter.objects.all()[:1].get()
    logo = med_center.photos.filter(is_logo=True).first()
    schedule_times = med_center.schedule_times.all()
    # branch
    main_branch = Branch.objects.get(med_center_id=med_center.id)
    main_branch_number = main_branch.numbers.first()

    context = {
        "med_center": med_center,
        "main_branch": main_branch,
        "main_branch_number": main_branch_number.number,
        "schedules": schedule_times,
        "logo": logo
    }

    return render(request, 'med_center/about.html', context=context)


def departments_page(request):
    # med center
    med_center = MedicalCenter.objects.all()[:1].get()
    logo = med_center.photos.filter(is_logo=True).first()
    schedule_times = med_center.schedule_times.all()
    # branch
    main_branch = Branch.objects.get(med_center_id=med_center.id)
    main_branch_number = main_branch.numbers.first()

    departments = Department.objects.all()

    dep = Department.objects.first()

    context = {
        "med_center": med_center,
        "main_branch": main_branch,
        "main_branch_number": main_branch_number.number,
        "schedules": schedule_times,
        "logo": logo,
        "departments": departments,
        "dep": dep
    }

    return render(request, 'med_center/departments.html', context=context)


def contacts_page(request):
    # med center
    med_center = MedicalCenter.objects.all()[:1].get()
    logo = med_center.photos.filter(is_logo=True).first()
    schedule_times = med_center.schedule_times.all()
    # branch
    main_branch = Branch.objects.get(med_center_id=med_center.id)
    main_branch_number = main_branch.numbers.first()

    doctors = Doctor.objects.filter(profile_id__is_superuser=False)
    context = {
        "med_center": med_center,
        "main_branch": main_branch,
        "main_branch_number": main_branch_number.number,
        "logo": logo,
        "schedules": schedule_times,
        "doctors": doctors
    }

    return render(request, 'med_center/contacts.html', context=context)


def main_page_view(request):
    # med center
    med_center = MedicalCenter.objects.all()[:1].get()
    logo = med_center.photos.filter(is_logo=True).first()
    schedule_times = med_center.schedule_times.all()
    # branch
    main_branch = Branch.objects.get(med_center_id=med_center.id)
    main_branch_number = main_branch.numbers.first()

    # user info
    user_role = None
    if request.user.is_authenticated:
        user_role = User.objects.get(id=request.user.id).role

    # departments
    departments = Department.objects.all()

    # services
    services = Service.objects.filter(department_id=departments.first())

    # doctors
    doctors = Doctor.objects.filter(profile_id__is_superuser=False)

    # reviews
    reviews = Review.objects.filter(is_approved=True).order_by('-created')[:4]

    # form
    form = AppointmentForm()

    context = {
        "med_center": med_center,
        "logo": logo,
        "schedules": schedule_times,
        "departments": departments,
        "services": services,
        "main_branch": main_branch,
        "main_branch_number": main_branch_number.number,
        "user_role": user_role,
        "doctors": doctors,
        "reviews": reviews,
        "form": form
    }
    return render(request, "med_center/index.html", context=context)

templates/med_center/about.html
{% extends 'med_center/index.html' %}
{% load static %}

{% block title %}
    О Мед. Центре
{% endblock %}

{% block content %}
  <section class="probootstrap-services">
    <div class="container">
      <div class="row no-gutters">
        <div class="col-md-3 pb-5 probootstrap-aside-stretch-left probootstrap-inside">
          <div class="mb-3 pt-5">
            <h2 class="h6">О нас</h2>
            <ul class="list-unstyled probootstrap-light mb-4">
              <li class="active"><a href="#">История</a></li>
            </ul>
          </div>
        </div>
        <div class="col-md-9 pl-md-5 pb-5 pl-0 probootstrap-inside">
          <h1 class="mt-4 mb-4">{{ med_center.title }}</h1>
            {{ med_center.description }}
          </div>
      </div>
    </div>
  </section>

{% endblock %}

templates/med_center/contacts.html
{% extends 'med_center/index.html' %}
{% load static %}

{% block title %}
    Контакты
{% endblock %}

{% block content %}
  <section class="probootstrap-services">
    <div class="container">
      <div class="row no-gutters">
        <div class="col-md-3 pb-5 probootstrap-aside-stretch-left probootstrap-inside">
          <div class="mb-3 pt-5 pr-2">
            <h2 class="h6">Контакты</h2>
{#            <ul class="list-unstyled probootstrap-light mb-4">#}
{#              <li class="active"><a href="#">Главный номер</a></li>#}
{#            </ul>#}
          </div>
        </div>
        <div class="col-md-9 pl-md-5 pb-5 pl-0 probootstrap-inside">
            <h1 class="mt-4 mb-4">Главный номер <span> > </span>{{ main_branch_number }}</h1>
            <h2>Доктора</h2>
            {% for doctor in doctors %}
                <h5>{{ doctor.profile_id.full_name }}</h5>
                {% for number in doctor.profile_id.userphonenumber_set.all %}
                    <p class="text-info" style=" margin-left: 10px;">{{ number.number }}</p>
                {% endfor %}
            {% endfor %}
        </div>
      </div>
    </div>
  </section>

{% endblock %}

templates/med_center/departments.html
{% extends 'med_center/index.html' %}
{% load static %}

{% block title %}
    Отделения
{% endblock %}

{% block content %}
  <section class="probootstrap-services">
    <div class="container">
      <div class="row no-gutters">
        <div class="col-md-3 pb-5 probootstrap-aside-stretch-left probootstrap-inside">
          <div class="mb-3 pt-5">
            <h2 class="h6">Отделения</h2>
            <ul class="list-unstyled probootstrap-light mb-4">
                {% for dep in departments %}
                    <li><a class="get-department">{{ dep.title }} <span id="{{ dep.id }}"></span></a></li>
                {% endfor %}
            </ul>
          </div>
        </div>
        <div class="col-md-9 pl-md-5 pb-5 pl-0 probootstrap-inside" id="department-detail">
          <h1 class="mt-4 mb-4">{{ dep.title }}</h1>
            <p>{{ dep.description }}</p>
        </div>
      </div>
    </div>
  </section>
    <script>
    $('.get-department').click(function (event) {
        var dep_id = $('span', this).attr('id');
        var dep_detail = $('#department-detail')

         $.ajax({
                url: '/api/department/' + dep_id + '/',
                method: 'GET',
                data: ({
                    'department_id': dep_id
                }),
                dataType: 'json',
                contentType: 'application/json',
                success: function (data) {
                    dep_detail.html('')
                    dep_detail.append(
                            render_department_section(data.department)
                    )
                },
                error: function (request, error) {
                    console.log(request);
                    console.log(error);
                }
            });
        console.log(dep_id);
        console.log("clicked");
    })

    function render_department_section(department) {
        html_item = '<h1 class="mt-4 mb-4">' + department.title + '</h1>\n' +
            '         <p> ' + department.description + ' </p>  '
        {#html_item = '<div class="col-lg-4 col-md-6">\n' +#}
        {#    '                    <div class="media d-block mb-4 text-left probootstrap-media">\n' +#}
        {#    '                        <div class="probootstrap-icon mb-3"><span class="flaticon-microscope display-4"></span></div>\n' +#}
        {#    '                          <div class="media-body">\n' +#}
        {#    '                            <h3 class="h5 mt-0 text-secondary">' + service_title + '</h3>\n' +#}
        {#    '                            <p> ' + service_price + ' сом </p>\n' +#}
        {#    '                          </div>\n' +#}
        {#    '                    </div>\n' +#}
        {#    '                  </div>'#}
        return html_item
    }
</script>

{% endblock %}